<?php

namespace HungerFirst\HFBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CheckoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckoutRepository extends EntityRepository
{
}
