<?php

namespace HungerFirst\HFBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WantedItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WantedItemRepository extends EntityRepository
{
}
