hf_homepage:
    path:     /
    defaults: { _controller: HFBundle:Default:index }

hf_customer_create:
    pattern: /customer/create
    defaults: { _controller: HFBundle:Customer:create }
    
hf_customer_edit:
    pattern: /customer/edit/{id}
    defaults: { _controller: HFBundle:Customer:edit, id: 0 }
    requirements:
        _method:  GET
        id:  \d+   