hf_index:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: hf_homepage
        permanent: true
hf_homepage:
    path:     /index/{page}/{id}/{firstName}/{lastName}/{address}/{phoneNumber}/{sortby}
    defaults: 
        _controller: HFBundle:Default:index
        page: 1
        id: 0
        firstName: "none"
        lastName: "none"
        address: "none"
        phoneNumber: "none"
        sortby: "none"
    requirements:
        _method:  GET
        id:  \d+   

hf_customer:
    pattern: /customer/{id}
    defaults: { _controller: HFBundle:Customer:view, id: 0 }
    requirements:
        _method:  GET
        id:  \d+   
        
hf_customer_create:
    pattern: /customer/create
    defaults: { _controller: HFBundle:Customer:create }
    
hf_customer_edit:
    pattern: /customer/edit/{id}
    defaults: { _controller: HFBundle:Customer:edit, id: 0 }
    requirements:
        id:  \d+   
        
hf_search_bar: 
    pattern: /search_bar
    defaults: { _controller: HFBundle:Customer:searchBar }       
        